### PR TITLE
feat: support brotli compression

### PR DESCRIPTION
**Pull request by ASaiAnudeep**
@ethanent please review it when you get a chance and upgrade it in the `phin`

### CODE REVIEW

**Comment by ethanent** [comment]
Thanks!

**Comment by ASaiAnudeep** [comment]
Hello @ethanent, thanks for merging. When can we expect this to be released and reflected in phin.

**Comment by ASaiAnudeep** [comment]
Hello @ethanent, apologies for the ping again. When can we expect this to be released and reflected in [phin](https://github.com/ethanent/phin).

**Comment by ASaiAnudeep** [comment]
Hello @ethanent, apologies for the ping once again. When can we expect this to be released and reflected in [phin](https://github.com/ethanent/phin). 🙇

**Comment by ethanent** [comment]
Hi @ASaiAnudeep, sorry for the delay on my end. Done.

**Pull request merged**
